### PR TITLE
Upgrade molo.core to 6.6.3

### PR DESCRIPTION
**Pull request by alexmuller**
https://github.com/praekelt/molo/compare/6.5.0...6.6.3

### CODE REVIEW

**Comment by saeedmb8** [comment]
@alexmuller please use 6.6.2 I have fix the migration issue in 6.6.0 in 6.6.2

**Comment by alexmuller** [comment]
@saeedmb8 Sure thing, done!

**Comment by saeedmb8** [comment]
@alexmuller I made a naming mistake in my migration :( I renamed it and created a new release. now the correct one is `6.3.3`. I will Update your PR as soon as the travis build is passed

**Comment by saeedmb8** [comment]
And I closed your PR 😭

**Comment by alexmuller** [comment]
That's ok, @codiebeulaine has bumped to a later version in her recent PR.

**Pull request closed without merging**
