### PR TITLE
Rearrange wagtail admin header - and comments filter table

### PR DESCRIPTION
**Pull request by Mitso**

### CODE REVIEW

**Comment by Mitso** [comment]
@nathanbegbie @saeedmb8 please review 

Please note inorder to tweak this, rearranging this is necessary as the HTML markup & CSS is written badly.

screenshot 2017-04-07 14 02 26

**Comment by nathanbegbie** [comment]
@Mitso There seems to be some side effects in the admin styling:
develop branch:
develop_branch
this branch:
this_branch

**Comment by nathanbegbie** [comment]
@Mitso :+1: :cake: yay for fixing our filter \o/

**Comment by miltontony** [comment]
🍰 🌟 💃 💥

**Comment by nathanbegbie** [comment]
Sorry, there seems to be an edge case here, where last item is cut short - just going to check if the error occurs with your changes.
screen shot 2017-04-07 at 5 39 28 pm

**Comment by nathanbegbie** [comment]
screen shot 2017-04-07 at 5 43 49 pm
screen shot 2017-04-07 at 5 43 54 pm
Okay for some reason the last item in the list appears to be cut short

**Comment by Mitso** [comment]
@nathanbegbie nice catch, 

Updated
screenshot 2017-04-07 18 08 49

**Comment by nathanbegbie** [comment]
@Mitso :+1:

**Pull request merged**
