### PR TITLE
prevent names with offensive language

### PR DESCRIPTION
**Pull request by TrevorOctober**

### CODE REVIEW

**Comment by TrevorOctober** [comment]
@saeedmb8 Ready for review

**Comment by TrevorOctober** [comment]
screen shot 2016-10-05 at 1 09 07 pm

**Comment by TrevorOctober** [comment]
check if user has used a banned name
screen shot 2016-10-05 at 1 10 32 pm

**Comment by TrevorOctober** [comment]
@saeedmb8 Ready for re-review

**Comment by saeedmb8** [comment]
👍  🍰  🍰

**Pull request merged**
