### PR TITLE
use manifest static file storage

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@JayH5 looks like it's still failing 😒

**Comment by JayH5** [comment]
_"Due to the requirement of running collectstatic, this storage typically shouldn’t be used when running tests as collectstatic isn’t run as part of the normal test setup. During testing, ensure that the STATICFILES_STORAGE setting is set to something else like 'django.contrib.staticfiles.storage.StaticFilesStorage' (the default)."_

https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/#manifeststaticfilesstorage

**Comment by miltontony** [comment]
ah.. I see in your PR it was working.. so I think it was fixed in `molo.core==5.5.0`

**Comment by JayH5** [comment]
@miltontony yeah I moved the `ManifestStaticFilesStorage` settings to `settings/production.py`.

**Pull request merged**
