### PR TITLE
enable template caching in production

### PR DESCRIPTION
**Pull request by miltontony**
Wagtail recommends enabling template caching to improve performance.
http://docs.wagtail.io/en/v1.9/advanced_topics/performance.html#templates

### CODE REVIEW

**Comment by miltontony** [comment]
@smn @saeedmb8 first PR for performance improvements.

**Comment by codiebeulaine** [comment]
@miltontony just curious, what does template caching mean? Does it mean we will only load content in prod and the template would load once and be cached?

**Comment by codiebeulaine** [comment]
👍

**Comment by smn** [comment]
@miltontony what does this cacher do? Saves the read from disk? I'm not sure it caches anything relating to DB queries though.

**Comment by miltontony** [comment]
@smn no, it doesn't do DB caching. Just disk.

**Comment by smn** [comment]
:+1:

**Pull request merged**
