### PR TITLE
Molo 360: Content wrap

### PR DESCRIPTION
**Pull request by Mitso**

### CODE REVIEW

**Comment by Mitso** [comment]
@codiebeulaine 
Please see content wrap updated.

**Comment by codiebeulaine** [comment]
@Mitso 👍 but can you upload a screenshot please?

**Comment by Mitso** [comment]
screenshot 2017-01-25 13 07 55

screenshot 2017-01-25 13 08 09

screenshot 2017-01-25 13 08 59

**Comment by codiebeulaine** [comment]
@Mitso thanks! 👍 🍰

**Pull request merged**
