### PR TITLE
Improved UX of registration

### PR DESCRIPTION
**Pull request by peterp**
@Mitso Can I get a +1?

Better error message, label is tappable, and looks like a link for checkbox.
screen shot 2016-06-13 at 15 18 16

Example of a PIN:
screen shot 2016-06-13 at 15 13 57

### CODE REVIEW

**Comment by Mitso** [comment]
@peterp the PIN example could be next to the label or part of the label for better UX as well. Both options work though just something to consider if not already :) 
+1

**Comment by peterp** [comment]
@Mitso like this?

screen shot 2016-06-13 at 15 35 58

**Comment by Mitso** [comment]
Actually worked well. Meant something like this:
screenshot

**Comment by peterp** [comment]
Aaaah, great call!

**Comment by Mitso** [comment]
Great! +1

**Pull request merged**
